grafana:
    image: jsdidierlaurent/rpi-grafana
    ports:
        - 3000:3000
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - /etc/grafana:/etc/grafana
    links:
        - influxdb
   
influxdb:
    build: docker/influxdb
    ports:
        - 8086:8086
        - 8088:8088
    expose:
        - 8086
    volumes:
        - /var/lib/influxdb:/var/lib/influxdb
        - /var/log/influxdb:/var/log/influxdb

python:
        build: docker/python
        volumes:
          ./bin:/usr/bin/smartbase  

supervisord:
    restart: always
    image: dockerfile/supervisor
    volumes:
        docker/supervisord/conf/master.conf:/etc/supervisor/conf.d 